# Generated by Django 5.2.9 on 2025-12-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindCare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialization', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Professional',
        ),
    ]
