# Generated by Django 5.2.9 on 2025-12-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindCare', '0002_professionalhelp_delete_professional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='image',
        ),
    ]
