# Generated by Django 5.2.9 on 2025-12-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindCare', '0005_journalentry_moodlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalhelp',
            name='name',
        ),
        migrations.RemoveField(
            model_name='professionalhelp',
            name='specialization',
        ),
        migrations.AddField(
            model_name='professionalhelp',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalhelp',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='professionalhelp',
            name='availability',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professionalhelp',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professionalhelp',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professionalhelp',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
